/** Sidebar/nav labels scraped from viltis.com — filtered out when parsing page body. */
export const NAV_NOISE = new Set([
  "Services",
  "Contact",
  "Contact us",
  "Quality",
  "Clinical",
  "Regulatory",
  "Engineering",
  "Scientific",
  "Pharmacovigilance",
  "GxP Compliance & Auditing",
  "Inspection Readiness (Quality)",
  "Computer System Validation (CSV)",
  "Commissioning, Qualification & Validation (CQV)",
  "Clinical Quality Assurance (CQA)",
  "Data Integrity & ALCOA+ Compliance",
  "QA for Digital Systems & Emerging Technologies",
  "Pharmaceutical",
  "Medical Devices",
  "Biologics",
  "Full-Service CRO",
  "Decentralized Clinical Trials",
  "Embedded Clinical Solutions",
  "Biostatistics & Programming",
  "Medical Writing & Transparency",
  "Clinical Operations Management",
  "Study Startup & Site Activation",
  "Clinical Data Management",
  "Real-World Evidence (RWE)",
  "FDA Regulatory Strategy and Consulting",
  "FDA Meeting Consulting Services",
  "Regulatory Operations",
  "Market Access & Reimbursement Strategy",
  "Advertising & Promotional Review (OPDP)",
  "Regulatory Intelligence & Guidance Monitoring",
  "FDA Inspection Readiness",
  "Post-Approval Regulatory Maintenance",
  "EU MDR (Medical Device Regulation)",
  "EU IVDR (In Vitro Diagnostic Regulation)",
  "Global Regulatory Considerations (FDA and EU MDR/IVDR)",
  "Facilities & Equipment Qualification",
  "Manufacturing Readiness & Technical Transfer",
  "Engineering Change Control & Lifecycle Management",
  "Utilities & Cleanroom Systems Qualification",
  "Process Engineering & Scale-Up Support",
  "Automation & Control Systems (GxP)",
  "Equipment Reliability & Preventive Maintenance",
  "Nonclinical Development",
  "Translational Science",
  "Scientific & Technical Consulting",
  "Bioanalytical Sciences",
  "Chemistry, Manufacturing, and Controls (CMC) scientific support",
  "Nonclinical Toxicology Strategy",
  "Biomarker Development & Validation",
  "Scientific Due Diligence & Program Assessment",
  "Adverse Event Reporting Across Clinical Trials and Post-Market",
  "Comprehensive ICSR Management for Global Compliance",
  "Proactive Signal Detection and Risk Management in Drug Safety",
  "Pharmacovigilance Gap Analysis: Strengthening Your Compliance Framework",
  "Post-Market Surveillance: Ensuring Ongoing Drug Safety",
  "Literature Surveillance for Pharmacovigilance: Tracking Emerging Risks",
  "Preparing for Pharmacovigilance Audits: Best Practices for Compliance",
  "Internal Pharmacovigilance Audits: Ensuring Regulatory Readiness",
  "The Role of the QPPV in Ensuring Global Pharmacovigilance Compliance",
  "Meeting European Pharmacovigilance Standards with QPPV Oversight",
  "Observational Studies and Real-World Evidence in Drug Safety",
  "Request a QA Contractor",
  "How Can We Help?",
  "Contact Us Today!",
  "News",
  "Archive",
  "Approach",
  "Strategic Consulting",
  "Dynamic Staff Augmentation",
  "Full-Time Expert Recruitment",
  "How Organizations Engage with Viltis",
  "Client Success Snapshot.",
  "Why Clients Choose Viltis",
  "Meet One of Our QA Experts",
  "Need GxP or ISO-Compliant QA Support?",
  "Audit-Ready Professionals",
  "Rapid Deployment",
  "Flexible stafting",
  "Mulit-industry coverage",
  "Gap Analysis and Consulting",
  "Literature Surveillance",
  "Pharmacovigilance Audits",
  "Qualified Person for Pharmacovigilance (QPPV)",
  "Observational Study Design",
]);
